### ISSUE TITLE
SNPeff and VEP for Ensembl release 102

### ISSUE THREAD

**Issue by ramirobarrantes** [annotation-cache/annotation-cache.github.io#6]
I need the versions of the cache for VEP and SNPEFF that correspond to ensembl release 102. This is relevant for all of us that use TCGA data as that is what they use. When I run:

`nextflow run nf-core/sarek -r 3.4.0 -profile singularity -work-dir work/ --outdir results/ --input sampleSheet.csv --fasta ../genome/GRCh38.d1.vd1.fa --fasta_fai ../genome/GRCh38.d1.vd1.fa.fai --snpeff_db 102 --vep_cache_version 102 --genome GATK.GRCh38  --tools strelka,vep,snpeff,merge`

I get 

> This path is not available within annotation-cache.
> Please check https://annotation-cache.github.io/ to create a request for it.
> Done.

**Comment by maxulysse** [comment]
we know have vep 102 for GRCh38, but 102 is not in snpeff
